fantasy:
    ccl: plass=fantasy
    human: Fantasy
    computer: fantasy
    ikkePregenerert: true
scifi:
    ccl: plass=scifi
    human: Science Fiction
    computer: scifi
spenning:
    ccl: (avd=ubhu eller avd=ubku) og plass=spenning
    human: Spenning
    computer: spenning
ungromaner:
    ccl: (avd=ubhu eller avd=ubku) og plass=romaner
    human: Vanlige bøker
    computer: ungromaner
tegneserier:
    ccl: plass=tegneserier
    human: Tegneserier
    computer: tegneserier
nynorskung:
    ccl: (avd=ubhp eller avd=ubkp eller avd=ubhu eller avd=ubku) og sp=nno
    human: Nynorsk
    computer: nynorskung